CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId integer REFERENCES projects(id)
)

INSERT INTO projects (name, priority, description, deliverydate)
        VALUES('Make a Web app', 1, 'Usibnng Javascript', '2022-02-25');

INSERT INTO projects (name, priority, description, deliverydate)
        VALUES('Make app', 3, 'Using Vue.js', '2022-04-25');

INSERT INTO projects (name, priority, description, deliverydate)
        VALUES('Study node.js', 5, 'Node.js', '2022-02-07');

INSERT INTO tasks (name, done, projectId)
    VALUES('Download vue.js', false, 2);

INSERT INTO tasks (name, done, projectId)
    VALUES('create ui web', false, 2);

INSERT INTO tasks (name, done, projectId)
    VALUES('Desing UI vue.js', false, 1);